name: Renovate trends cron

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get last commit message
        id: get-msg
        run: |
          echo "{msg}={git log -1 HEAD --pretty=format:%s}" >> $GITHUB_ENV
      - name: Use correct Node.js version
        run: nvm use
      - name: Install dependencies
        run: npm i
      - name: Fetch latest & register
        run: npm start
      - name: Add & Commit-Amend
        if: contains(${{ env.msg }}, 'Renovate CRAN/E trends')
        uses: EndBug/add-and-commit@v9.1.0
        with:
          add: '.'
          message: 'Renovate CRAN/E trends'
          default_author: 'github_actions'
          commit: '--amend'
          push: --force-with-lease
      - name: Add & Commit
        if: "!contains(${{ env.msg }}, 'Renovate CRAN/E trends')"
        uses: EndBug/add-and-commit@v9.1.0
        with:
          add: '.'
          message: 'Renovate CRAN/E trends'
          default_author: 'github_actions'
